export const ship = {
  icon: "images/naves/1.jpeg",
  name: "Cazador Estelar Aether",
  combustible: 0,
  almacenaje: [],
  escudos: 0,
  armamento: 50,
};

export const newShip = () => {
  const idMaxImage = 38;
  const idImage = getRandomInt(1, idMaxImage);

  const planet = {
    icon: `images/naves/${idImage}.jpeg`,
    name: generateShipName(),
    combustible: getRandomInt(1, 100),
    almacenaje: getRandomInt(1, 100),
    escudos: getRandomInt(60, 80),
    armamento: getRandomInt(10, 25),
  };

  function getRandomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1) + min);
  }

  function generateShipName() {
    const prefixes = [
      "Star",
      "Galactic",
      "Cosmic",
      "Interstellar",
      "Nebula",
      "Quantum",
      "Celestial",
      "Astro",
      "Space",
      "Nova",
      "Eclipse",
      "Vortex",
      "Pulsar",
      "Infinity",
      "Stellar",
      "Aurora",
      "Hyper",
      "Orion",
      "Solar",
      "Lunar",
      "Apollo",
      "Astral",
      "Ultraviolet",
      "Infinite",
      "Plasma",
      "Cosmos",
      "Comet",
      "Nebula",
      "Spectral",
      "Lunar",
      "Supernova",
      "Andromeda",
      "Voyager",
      "Galaxy",
      "Ethereal",
      "Radiant",
      "Titan",
      "Omega",
      "Cosmic",
      "Zephyr",
      "Astro",
      "Serenity",
      "Quantum",
      "Spectre",
      "Pioneer",
      "Starlight",
      "Infinity",
      "Cerulean",
      "Vertex",
      "Sapphire",
      "Nemesis",
      "Apollo",
      "Stellar",
      "Luminous",
      "Solaris",
      "Aether",
      "Xenon",
      "Polaris",
      "Nyx",
      "Aegis",
      "Phoenix",
      "Olympus",
      "Horizon",
      "Elysium",
      "Cynosure",
      "Lyra",
      "Solstice",
      "Eon",
      "Eclipse",
      "Voyage",
      "Astrum",
      "Axiom",
      "Hyperion",
      "Genesis",
      "Nebulous",
      "Astoria",
      "Catalyst",
      "Zodiac",
      "Vortex",
      "Nimbus",
      "Sylvan",
      "Seraph",
      "Aurora",
      "Luminar",
      "Solarium",
      "Ignition",
      "Apex",
      "Nebular",
      "Halcyon",
      "Quantum",
      "Expanse",
      "Aegis",
      "Aquila",
      "Zephyr",
      "Orion",
      "Vanguard",
      "Aetherial",
      "Apogee",
      "Zenith",
      "Umbra",
    ];
    const suffixes = [
      "Explorer",
      "Voyager",
      "Navigator",
      "Odyssey",
      "Pioneer",
      "Sentinel",
      "Argonaut",
      "Nomad",
      "Guardian",
      "Ranger",
      "Seeker",
      "Harbinger",
      "Phoenix",
      "Cruiser",
      "Scout",
      "Hunter",
      "Raider",
      "Spectre",
      "Specter",
      "Shuttle",
      "Lancer",
      "Interceptor",
      "Custodian",
      "Defender",
      "Frigate",
      "Vigilant",
      "Pilgrim",
      "Marauder",
      "Sovereign",
      "Corsair",
      "Nomad",
      "Rover",
      "Starfighter",
      "Aviator",
      "Pathfinder",
      "Corsair",
      "Wanderer",
      "Vanguard",
      "Quasar",
      "Inquisitor",
      "Emissary",
      "Starship",
      "Drifter",
      "Rover",
      "Strider",
      "Warden",
      "Starhawk",
      "Nighthawk",
      "Crusader",
      "Vindicator",
      "Expedition",
      "Sparrow",
      "Spectra",
      "Skyward",
      "Vortex",
      "Dreadnought",
      "Nucleus",
      "Helix",
      "Aegis",
      "Nexus",
      "Scepter",
      "Cynosure",
      "Genesis",
      "Starlight",
      "Eon",
      "Horizon",
      "Epoch",
      "Eclipse",
      "Apex",
      "Solaris",
      "Luminar",
      "Astrum",
      "Aeon",
      "Synergy",
      "Aurora",
      "Elysium",
      "Centauri",
      "Aquila",
      "Zephyr",
      "Polaris",
      "Aether",
      "Nebula",
      "Halcyon",
      "Quantum",
      "Serpentis",
      "Viper",
      "Crux",
      "Polaris",
      "Lyra",
      "Celestia",
      "Nimbus",
      "Zenith",
      "Umbra",
      "Cirrus",
      "Altair",
      "Rigel",
      "Aldebaran",
      "Vela",
      "Astralis",
      "Galaxia",
    ];

    const randomPrefix = prefixes[Math.floor(Math.random() * prefixes.length)];
    const randomSuffix = suffixes[Math.floor(Math.random() * suffixes.length)];

    return randomPrefix + " " + randomSuffix;
  }

  return planet;
};
