export const universe = {
  background: "images/backgrounds/universe.jpeg",
  icon: "images/backgrounds/universe.jpeg",
  name: "Espacio",
  temperatura: 0,
  gravedad: 0,
  porcentajeTierra: 0,
  size: 100,
};

export const baseWorld = {
  background: "images/hangares/hangar4.jpeg",
  icon: "images/hangares/hangar4.jpeg",
  name: "Estación Espacial",
  temperatura: 14,
  gravedad: 10,
  porcentajeTierra: 30,
  size: 6,
};

export const newWorld = () => {
  const idMaxImage = 26;
  const idImage = getRandomInt(1, idMaxImage);

  const planet = {
    background: `images/backgrounds/${idImage}.jpeg`,
    icon: `images/worlds/${idImage}.jpeg`,
    name: generatePlanetName(),
    temperatura: getRandomInt(1, 100),
    gravedad: getRandomInt(1, 30),
    porcentaje: getRandomInt(1, 100),
    size: getRandomInt(1, 10),
  };

  function getRandomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1) + min);
  }

  function generatePlanetName() {
    const prefixes = [
      "Alpha",
      "Beta",
      "Gamma",
      "Delta",
      "Epsilon",
      "Zeta",
      "Eta",
      "Theta",
      "Iota",
      "Kappa",
      "Lambda",
      "Mu",
      "Nu",
      "Xi",
      "Omicron",
      "Pi",
      "Rho",
      "Sigma",
      "Tau",
      "Upsilon",
      "Phi",
      "Chi",
      "Psi",
      "Omega",
      "Astra",
      "Celestial",
      "Nebula",
      "Galactic",
      "Stellar",
      "Cosmic",
      "Interstellar",
      "Solar",
      "Lunar",
      "Terrestrial",
      "Exoplanet",
      "Orbital",
      "Radiant",
      "Infinite",
      "Eternal",
      "Vivid",
      "Spectral",
      "Pulsar",
      "Quasar",
      "Singular",
      "Abyssal",
      "Vortex",
      "Ethereal",
      "Chrono",
      "Prismatic",
      "Nova",
      "Quantum",
      "Seraph",
      "Void",
      "Orion",
      "Pegasus",
      "Andromeda",
      "Cygnus",
      "Phoenix",
      "Aurora",
      "Lyra",
      "Proxima",
      "Centauri",
      "Sirius",
      "Pluto",
      "Venus",
      "Mars",
      "Jupiter",
      "Saturn",
      "Neptune",
      "Uranus",
      "Mercury",
      "Luna",
      "Terra",
      "Aurum",
      "Aether",
      "Titan",
      "Hyperion",
      "Atlantis",
      "Xanadu",
      "Elysium",
      "Olympus",
      "Nebulae",
      "Supernova",
      "Voyager",
      "Umbra",
      "Celesta",
      "Lumina",
      "Zephyr",
      "Cosmos",
      "Radiance",
      "Horizon",
      "Quintessence",
      "Harmony",
      "Astral",
      "Zenith",
      "Solstice",
      "Epoch",
      "Infinity",
      "Serenity",
      "Astro",
      "Pinnacle",
      "Vortex",
      "Zenon",
      "Axiom",
      "Polaris",
    ];
    const suffixes = [
      " Prime",
      " Minor",
      " Major",
      " Exo",
      " Nova",
      " Core",
      " Frontier",
      " Outpost",
      " Oasis",
      " Haven",
      " Haven",
      " Citadel",
      " Outlands",
      " Abyss",
      " Sanctuary",
      " Sanctum",
      " Gateway",
      " Nexus",
      " Horizon",
      " Shores",
      " Gateway",
      " Oasis",
      " Periphery",
      " Hub",
      " Oasis",
      " Enclave",
      " Spire",
      " Ascent",
      " Summit",
      " Pinnacle",
      " Echo",
      " Horizon",
      " Apex",
      " Zenith",
      " Depths",
      " Depths",
      " Peril",
      " Rift",
      " Vortex",
      " Abyss",
      " Sanctum",
      " Utopia",
      " Zenith",
      " Rift",
      " Oracle",
      " Sanctuary",
      " Echo",
      " Oasis",
      " Monolith",
      " Shores",
      " Frontier",
      " Outpost",
      " Zenith",
      " Utopia",
      " Horizon",
      " Shores",
      " Sanctuary",
      " Gateway",
      " Haven",
      " Depths",
      " Frontier",
      " Spire",
      " Oracle",
      " Peril",
      " Depths",
      " Depths",
      " Pinnacle",
      " Outpost",
      " Monolith",
      " Summit",
      " Shores",
      " Utopia",
      " Sanctuary",
      " Monolith",
      " Spire",
      " Summit",
      " Outlands",
      " Pinnacle",
      " Depths",
      " Haven",
      " Nexus",
      " Pinnacle",
      " Spire",
      " Monolith",
      " Pinnacle",
      " Shores",
      " Depths",
      " Depths",
      " Sanctuary",
      " Depths",
      " Oasis",
      " Monolith",
      " Gateway",
      " Pinnacle",
      " Enclave",
      " Shores",
      " Oasis",
      " Summit",
      " Echo",
      " Oracle",
      " Outpost",
      " Sanctuary",
      " Spire",
      " Haven",
      " Utopia",
      " Oasis",
      " Depths",
      " Echo",
      " Outpost",
      " Peril",
      " Sanctuary",
      " Zenith",
      " Gateway",
      " Utopia",
      " Outpost",
      " Shores",
      " Depths",
      " Shores",
      " Oasis",
      " Depths",
      " Summit",
      " Haven",
      " Zenith",
      " Depths",
      " Shores",
    ];

    const randomPrefix = prefixes[Math.floor(Math.random() * prefixes.length)];
    const randomSuffix = suffixes[Math.floor(Math.random() * suffixes.length)];

    return randomPrefix + " " + randomSuffix;
  }

  return planet;
};
